"""add calendar source credential fields

Revision ID: e493e865595a
Revises: 1205c39896d4
Create Date: 2026-03-14 18:39:55.465969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e493e865595a'
down_revision = '1205c39896d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_profile_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('source_profile_name', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_calendars_source_profile_id'), ['source_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendars_source_profile_id'))
        batch_op.drop_column('source_profile_name')
        batch_op.drop_column('source_profile_id')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
